version: '2'
services:
  dev:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    image: keboola/ex_teradata
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - TERADATA_HOST
      - TERADATA_PORT
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_DATABASE
