version: '2'
services:
  app:
    build: .
    image: keboola/ex_teradata
    volumes:
      - ./:/code
      - ./data:/data
  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: ./code-coverage.sh
